const $=s=>document.querySelector(s);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const menu=$('#menu'),button=$('#menuButton'),main=$('main'),header=$('header'),opening=$('#opening');
let introTimer,exitTimer;
function finishIntro(){clearTimeout(introTimer);clearTimeout(exitTimer);document.documentElement.classList.add('intro-complete');document.body.classList.remove('opening-running');opening.setAttribute('aria-hidden','true');main.inert=false;header.inert=false;}
function exitIntro(){if(document.documentElement.classList.contains('intro-complete'))return;clearTimeout(introTimer);opening.classList.add('departing');exitTimer=setTimeout(finishIntro,reduced.matches?0:1300);}
function startIntro(){clearTimeout(introTimer);clearTimeout(exitTimer);if(reduced.matches||location.hash){finishIntro();return;}document.documentElement.classList.remove('intro-complete');opening.classList.remove('departing');opening.removeAttribute('aria-hidden');document.body.classList.add('opening-running');main.inert=true;header.inert=true;opening.querySelectorAll('.signature,.signature-stroke,.opening-note,.opening-bottom').forEach(el=>{el.getAnimations().forEach(a=>{a.cancel();a.play();});});introTimer=setTimeout(exitIntro,2700);}
$('#skipIntro').addEventListener('click',()=>{finishIntro();button.focus();});
$('#replayIntro').addEventListener('click',()=>{history.replaceState(null,'',location.pathname);window.scrollTo({top:0,behavior:'instant'});startIntro();});
function closeMenu(){menu.close();button.setAttribute('aria-expanded','false');document.body.style.overflow='';button.focus();}
button.addEventListener('click',()=>{menu.showModal();button.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';});
$('#closeMenu').addEventListener('click',closeMenu);menu.addEventListener('cancel',e=>{e.preventDefault();closeMenu();});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.05});
document.querySelectorAll('.project,.intro h2,.background>div,.credential,.building-grid,.community figure').forEach(el=>{el.classList.add('reveal');observer.observe(el);});
const hero=$('.hero'),portrait=$('.portrait'),intro=$('.intro'),journey=$('.journey'),work=$('.work'),bio=$('.background'),footer=$('footer');
const chapters=[...document.querySelectorAll('.motion-chapter')],rail=[...document.querySelectorAll('.chapter-rail i')],projects=[...document.querySelectorAll('.project')];
const canvas=$('#flowCanvas'),ctx=canvas.getContext('2d',{alpha:false});
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
let w=innerWidth,h=innerHeight,scrollTarget=scrollY,scrollCurrent=scrollY,phase=0,frame=0,activeChapter=-1,visibleFlow=false;
function resize(){w=innerWidth;h=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);requestFrame();}
function drawFlow(progress){if(!ctx)return;ctx.fillStyle='#100909';ctx.fillRect(0,0,w,h);const hue=progress<.34?22+progress*220:Math.max(8,97-(progress-.34)*180);const glow=ctx.createRadialGradient(w*.5,h*.48,10,w*.5,h*.48,Math.max(w,h)*.65);glow.addColorStop(0,`hsla(${hue},70%,20%,.45)`);glow.addColorStop(1,'#100909');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);const size=Math.max(w,h)*.72;const turn=progress*5.5+phase;const morph=Math.sin(progress*Math.PI);ctx.save();ctx.translate(w*.5,h*.48);ctx.rotate(turn*.12);ctx.globalCompositeOperation='screen';const rings=w<600?28:44;for(let j=rings;j>0;j--){const t=j/rings;const radius=size*Math.pow(t,1.8);ctx.beginPath();for(let k=0;k<=100;k++){const a=k/100*Math.PI*2;const swirl=a+turn+(1-t)*2.8;const wave=1+.24*Math.sin(a*3+turn*.7)+.15*morph*Math.cos(a*2-turn);const r=radius*wave;const x=Math.cos(swirl)*r*(1+.25*morph);const y=Math.sin(swirl)*r*.78;const drift=Math.sin(t*5+turn)*size*.035;(k?ctx.lineTo(x+drift,y):ctx.moveTo(x+drift,y));}ctx.closePath();ctx.strokeStyle=`hsla(${hue+t*18},80%,${38+t*24}%,${.08+Math.sin(t*Math.PI)*.27})`;ctx.lineWidth=1+t*2.5;ctx.stroke();}ctx.restore();}
function update(){frame=0;scrollTarget=scrollY;scrollCurrent+= (scrollTarget-scrollCurrent)*.12;if(Math.abs(scrollTarget-scrollCurrent)<.2)scrollCurrent=scrollTarget;const y=scrollCurrent;header.classList.toggle('scrolled',scrollY>100);const root=document.documentElement;root.style.setProperty('--read',`${clamp(scrollY/(root.scrollHeight-h))*100}%`);const jr=journey.getBoundingClientRect();const progress=clamp(-jr.top/Math.max(1,journey.offsetHeight-h));const chapter=Math.min(3,Math.floor(progress*4));if(activeChapter!==chapter){activeChapter=chapter;chapters.forEach((el,i)=>{el.classList.toggle('active',i===chapter);el.inert=!reduced.matches&&i!==chapter;el.setAttribute('aria-hidden',String(!reduced.matches&&i!==chapter));});rail.forEach((el,i)=>el.classList.toggle('active',i===chapter));}
if(!reduced.matches){const hp=clamp(y/Math.max(1,hero.offsetHeight-h));hero.style.setProperty('--name-x',`${-hp*w*.12}px`);hero.style.setProperty('--name-y',`${-hp*80}px`);hero.style.setProperty('--name-opacity',`${1-hp*.6}`);hero.style.setProperty('--orbit-turn',`${hp*120}deg`);hero.style.setProperty('--hero-radius',`${hp*80}px`);portrait.style.transform=`translate3d(${-hp*w*.04}px,${hp*25}px,0) rotate(${hp*3}deg) scale(${1+hp*.08})`;const ir=intro.getBoundingClientRect();intro.style.setProperty('--ink-progress',`${clamp((h-ir.top)/(h*.8))*100}%`);intro.style.setProperty('--intro-radius',`${(1-clamp((h-ir.top)/h))*80}px`);work.style.setProperty('--heading-x',`${clamp((work.getBoundingClientRect().top-h*.4)/h,-1,1)*55}px`);projects.forEach(el=>{const r=el.getBoundingClientRect();if(r.top>h*1.5||r.bottom<-h*.5)return;const p=clamp((r.top+r.height*.5-h*.5)/h,-1,1);el.style.setProperty('--art-y',`${p*(w<600?18:50)}px`);el.style.setProperty('--art-tilt',`${p*5}deg`);el.style.setProperty('--copy-y',`${p*-18}px`);});const br=bio.getBoundingClientRect();bio.style.setProperty('--bio-radius',`${clamp(br.top/h)*90}px`);footer.style.setProperty('--contact-y',`${clamp(footer.getBoundingClientRect().top/h)*65}px`);}
visibleFlow=jr.top<h&&footer.getBoundingClientRect().top>0;
if(visibleFlow||reduced.matches){phase+=reduced.matches?0:.0015;drawFlow(progress+(scrollY>work.offsetTop?clamp((scrollY-work.offsetTop)/work.offsetHeight)*.7:0));}
if(!document.hidden&&!reduced.matches&&(visibleFlow||scrollCurrent!==scrollTarget))frame=requestAnimationFrame(update);
}
function requestFrame(){if(!frame)frame=requestAnimationFrame(update);}
addEventListener('scroll',requestFrame,{passive:true});addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;}else requestFrame();});reduced.addEventListener('change',()=>{if(reduced.matches)finishIntro();activeChapter=-1;requestFrame();});
startIntro();resize();drawFlow(0);
